# Generated by Django 4.1.2 on 2022-10-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.IntegerField(default=1, verbose_name='Percentage(%)')),
                ('reserve', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_in', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transferred', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
