# Generated by Django 4.1.2 on 2022-10-16 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funds',
            new_name='Fund',
        ),
    ]
