# Generated by Django 4.1.2 on 2022-10-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_funds_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='cash_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fund',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fund',
            name='received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fund',
            name='reserve',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fund',
            name='transferred',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
