# Generated by Django 4.1.2 on 2022-10-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_fund_cash_in_alter_fund_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='type',
            field=models.CharField(choices=[('Company Management', 'Company Management'), ('Payout Management', 'Payout Management')], default='Company Management', max_length=100),
        ),
    ]
