# Generated by Django 4.1.2 on 2022-10-16 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fund_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cash_in', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Depot_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Dealer_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Agent_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Total_payout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_from', models.CharField(choices=[('Registration', 'Registration'), ('Re-Purchase', 'Re-Purchase')], default='Registration', max_length=100)),
                ('at_cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('at_point', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('Member', 'Member'), ('Stockiest', 'Stockiest')], default='Member', max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fund_transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transfer_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_from', to='core.fund')),
                ('transfer_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to', to='core.fund')),
            ],
        ),
    ]
