# Generated by Django 4.1.2 on 2022-10-17 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bonus_sales_withdraw_fund_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='received',
            new_name='recieved',
        ),
    ]
