# Generated by Django 4.0.5 on 2022-10-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_received_fund_recieved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product/thumbnail')),
            ],
        ),
    ]
