# Generated by Django 4.1.2 on 2022-11-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_rename_price_product_trade_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='calculate_on',
            field=models.CharField(choices=[('TP', 'TP'), ('MRP', 'MRP')], default='TP', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='customfunds',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/thumbnail'),
        ),
    ]
