# Generated by Django 4.1.2 on 2022-11-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_fund_calculate_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='calculate_on',
        ),
    ]
