# Generated by Django 4.1.2 on 2022-11-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_fund_calculate_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='calculate_on',
            field=models.CharField(choices=[('POINT', 'POINT'), ('TP', 'TP'), ('MRP', 'MRP')], default='POINT', max_length=20),
        ),
    ]
