# Generated by Django 4.1.2 on 2022-11-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
