# Generated by Django 4.1.2 on 2022-11-20 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_member_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='sponsor_memeber',
            new_name='sponsor_member',
        ),
    ]
