# Generated by Django 4.1.2 on 2022-11-20 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_sponsor_memeber_member_sponsor_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='sponsor_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sponsor_agent', to='core.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sponsor_dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sponsor_dealer', to='core.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sponsor_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sponsor_depot', to='core.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='sponsor_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Sponsor_member', to='core.member'),
        ),
    ]
