# Generated by Django 4.1.2 on 2022-12-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_member_sponsor_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='placement_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='placement_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_b', to='core.member'),
        ),
    ]
