# Generated by Django 4.1.2 on 2023-01-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_member_placement_a_member_placement_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('MEMBER', 'MEMBER'), ('AGENT', 'AGENT'), ('DEALER', 'DEALER'), ('DEPOT', 'DEPOT')], default='MEMBER', max_length=10),
        ),
    ]
