# Generated by Django 4.1.2 on 2023-01-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_stockiest_product_stockiest_invoice_member_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_invoice',
            name='Members_products',
        ),
        migrations.RemoveField(
            model_name='stockiest_invoice',
            name='Stockiests_products',
        ),
        migrations.AddField(
            model_name='member_invoice',
            name='Members_products',
            field=models.ManyToManyField(to='core.member_product'),
        ),
        migrations.AddField(
            model_name='stockiest_invoice',
            name='Stockiests_products',
            field=models.ManyToManyField(to='core.stockiest_product'),
        ),
    ]
