# Generated by Django 4.1.2 on 2023-01-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_member_invoice_members_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockiest_invoice',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='stockiest_product',
            name='completed',
        ),
        migrations.AddField(
            model_name='stockiest_product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockiest_invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
