# Generated by Django 4.1.2 on 2023-01-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_stockiest_invoice_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockiest_invoice',
            name='totalbp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
