# Generated by Django 4.1.2 on 2023-01-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_stockiest_invoice_totalbp'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
