# Generated by Django 4.1.2 on 2023-01-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_member_collective_bp_a_member_collective_bp_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='matched_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
