# Generated by Django 4.1.2 on 2023-01-31 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_member_invoice_stockiest_member_product_stockiest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_product',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stockiest_product'),
        ),
    ]
