# Generated by Django 4.1.2 on 2023-01-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_member_product_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_invoice',
            name='totalbp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
